# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
  - package-ecosystem: "gomod"
    directory: "/" # Location of package manifests
    schedule:
      interval: "monthly"
    ignore:
    # Ignore k8s.io/* as its upgraded manually.
    - dependency-name: "k8s.io/apimachinery"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
    - dependency-name: "k8s.io/api"
      update-types: ["version-update:semver-major", "version-update:semver-minor"]
    - dependency-name: "github.com/rancher/client-go"
