# This workflow calls the main workflow with custom variables
name: GKE-E2E
run-name: GKE ${{ inputs.downstream_k8s_minor_version }} on Rancher v${{ inputs.rancher_version || '2.9-head' }} deployed on ${{ inputs.k3s_version || 'v1.28.9+k3s1' }}

on:
  schedule:
    - cron: "0 4 * * *" # Run every day
  workflow_dispatch: # Allow running manually on demand
    inputs:
      rancher_version:
        description: Rancher version to deploy
        required: true
        type: string
        default: 2.9-head
      k3s_version:
        description: k3s version of local cluster
        required: true
        type: string
        default: v1.28.9+k3s1
      runner_template:
        description: Runner template to use
        default: hosted-prov-e2e-ci-runner-spot-n2-highmem-16-gl-template-v2
        type: string
      operator_nightly_chart:
        description: Install hosted-provider nightly chart
        default: true
        required: true
        type: boolean
      destroy_runner:
        description: Destroy the auto-generated self-hosted runner
        default: true
        type: boolean
      downstream_cluster_cleanup:
        description: Cleanup downstream clusters after test
        default: true
        type: boolean
      downstream_k8s_minor_version:
        description: Downstream cluster minor K8s version to test (e.g. 1.28)
      rancher_installed:
        description: Rancher details if already installed
        default: 'hostname/password'
        type: string
      tests_to_run:
        description: Tests to run (p0_provisioning/p0_import/p1_provisioning/p1_import/support_matrix_provisioning/support_matrix_import/k8s_chart_support_provisioning/k8s_chart_support_import/sync_provisioning/sync_import)
        type: string
        required: true
        default: p0_provisioning/p0_import

jobs:
  gke-e2e:
    uses: ./.github/workflows/main.yaml
    secrets: inherit
    with:
      hosted_provider: gke
      rancher_version: ${{ inputs.rancher_version || '2.9-head' }}
      k3s_version: ${{ inputs.k3s_version || 'v1.28.9+k3s1' }}
      operator_nightly_chart: ${{ inputs.operator_nightly_chart == true || (github.event_name == 'schedule' && true) }}
      tests_to_run: ${{ inputs.tests_to_run || 'p0_provisioning/p0_import' }}
      destroy_runner: ${{ inputs.destroy_runner ==true || (github.event_name == 'schedule' && true) }}
      runner_template: ${{ inputs.runner_template || 'hosted-prov-e2e-ci-runner-spot-n2-highmem-16-gl-template-v2' }}
      downstream_k8s_minor_version: ${{ inputs.downstream_k8s_minor_version }}
      rancher_installed: ${{ inputs.rancher_installed || 'hostname/password' }}
      downstream_cluster_cleanup: ${{ inputs.downstream_cluster_cleanup == true || (github.event_name == 'schedule' && true) }}
