# This workflow calls the main workflow with custom variables
name: GKE-E2E
run-name: GKE ${{ inputs.downstream_k8s_minor_version }} on Rancher ${{ inputs.rancher_version || 'latest/devel/2.8' }} deployed on ${{ inputs.k3s_version || 'v1.27.9+k3s1' }}

on:
  workflow_dispatch: # Allow running manually on demand
    inputs:
      rancher_version:
        description: Rancher version channel/version/head_version latest/latest, latest/2.9.3[-rc2], prime/2.9.3, prime/devel/2.9, prime-optimus/2.9.3-rc2
        required: true
        type: string
        default: latest/devel/2.8
      k3s_version:
        description: k3s version of local cluster
        required: true
        type: string
        default: v1.27.9+k3s1
      runner_template:
        description: Runner template to use
        default: hosted-prov-e2e-ci-runner-spot-n2-highmem-16-gl-template-v3
        type: string
      operator_nightly_chart:
        description: Install hosted-provider nightly chart
        default: true
        required: true
        type: boolean
      destroy_runner:
        description: Destroy the auto-generated self-hosted runner
        default: true
        type: boolean
      downstream_cluster_cleanup:
        description: Cleanup downstream clusters after test
        default: true
        type: boolean
      downstream_k8s_minor_version:
        description: Downstream cluster minor K8s version to test (e.g. 1.28)
      rancher_installed:
        description: Rancher details if already installed
        default: 'hostname/password'
        type: string
      tests_to_run:
        description: Tests to run (p0_provisioning/p0_importing/p1_provisioning/p1_importing/support_matrix_provisioning/support_matrix_importing/k8s_chart_support_provisioning/k8s_chart_support_importing)
        type: string
        required: true
        default: p0_provisioning/p0_importing
      proxy:
        description: Install Rancher behind proxy
        type: boolean
        default: false

jobs:
  gke-e2e:
    uses: ./.github/workflows/main.yaml
    secrets: inherit
    with:
      hosted_provider: gke
      rancher_version: ${{ inputs.rancher_version || 'latest/devel/2.8' }}
      k3s_version: ${{ inputs.k3s_version || 'v1.27.9+k3s1' }}
      operator_nightly_chart: ${{ inputs.operator_nightly_chart == true }}
      tests_to_run: ${{ inputs.tests_to_run || 'p0_provisioning/p0_importing' }}
      destroy_runner: ${{ inputs.destroy_runner == true }}
      runner_template: ${{ inputs.runner_template || 'hosted-prov-e2e-ci-runner-spot-n2-highmem-16-gl-template-v3' }}
      downstream_k8s_minor_version: ${{ inputs.downstream_k8s_minor_version }}
      rancher_installed: ${{ inputs.rancher_installed || 'hostname/password' }}
      downstream_cluster_cleanup: ${{ inputs.downstream_cluster_cleanup == true }}
      proxy: ${{ inputs.proxy }}
